$\alpha$와 $\beta$는 같다.

$$\alpha = \beta$$

In [5]:
# 영벡터
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# 일벡터
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# 정방 행렬
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [8]:
# 항등 행렬
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 연습 문제 2.2.1
A,B,C 세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.
- (1) 주식의 가격과 수량을 각각 p벡터, n벡터로 표시하고 넘파이로 코딩한다.
- (2) 주식을 매수할 때 필요한 금액을 곱셈으로 표시하고 넘파이 연산으로 그 값을 계산한다.

In [10]:
p = np.array([100,80,50])
n = np.array([3,4,5])
p, n

(array([100,  80,  50]), array([3, 4, 5]))

In [15]:
# 벡터의 내적을 구하는 방식 2가지 (1차원 배열은 전치를 하지 않고 계산 가능, 2차원 배열은 앞에 벡터를 전치해줘야한다.)
p @ n, np.dot(p, n)

(870, 870)

###  연습 문제 2.2.3
다음 코드를 실행하면 MNIST 숫자 이미지 전체 데이터를 모두 벡터로 변환하여 하나의 넘파이 행렬 X를 만든다. 이 행렬을 이용하여 다음 문제를 풀어라.

- from sklearn.datasets import load_digits
- X = load_digits().data

In [11]:
from sklearn.datasets import load_digits
X = load_digits().data

X[0].T @ X[9]

2807.0

### 연습 문제 2.2.4 
- (1) A, B가 다음과 같을 때, AB, BA를 계산한다.
    - A = np.array([1,2,3])
    - B = np.array([[4,7], [5,8], [6,9]])
- (2) A, B가 다음과 같을 때, AB, BA를 계산한다.
    - A = np.array([[1, 2], [3, 4]])
    - B = np.array([[5, 6], [7, 8]])
- (3) A가 다음과 같을 때, AA.T, A.TA를 계산한다.
- (4) x가 다음과 같을 때, x.Tx, xx.T를 계산한다.

In [18]:
# (1)
A = np.array([1,2,3])
B = np.array([[4,7], [5,8], [6,9]])

In [16]:
A @ B

array([32, 50])

In [17]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [19]:
# (2)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [20]:
A @ B, B @ A

(array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]))

In [21]:
# (3)
A = np.array([[1, 2], [3, 4], [5, 6]])

In [22]:
A.T @ A, A @ A.T

(array([[35, 44],
        [44, 56]]),
 array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]]))

In [26]:
# (4)
x = np.array([[1],[2],[3]])

In [27]:
x.T @ x, x @ x.T

(array([[14]]),
 array([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]]))

### 연습 문제 2.2.5

In [41]:
ones = np.ones(5)
x = np.array([5,5,5,5,5])
ones @ x.T

25.0

In [47]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
ones = np.ones((3,1))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
x.T @ ones / 3

array([[4.],
       [5.],
       [6.]])

In [57]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
ones = np.ones((3,1))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
ones @ ones.T @ x / 3

array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]])

In [70]:
from sklearn.datasets import load_iris
x = load_iris().data
ones = np.ones((150, 1))
ones @ ones.T @ x / 150

array([[5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333,