$\alpha$와 $\beta$는 같다.

$$\alpha = \beta$$

In [5]:
# 영벡터
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# 일벡터
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# 정방 행렬
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [8]:
# 항등 행렬
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 연습 문제 2.2.1
A,B,C 세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.
- (1) 주식의 가격과 수량을 각각 p벡터, n벡터로 표시하고 넘파이로 코딩한다.
- (2) 주식을 매수할 때 필요한 금액을 곱셈으로 표시하고 넘파이 연산으로 그 값을 계산한다.

In [10]:
p = np.array([100,80,50])
n = np.array([3,4,5])
p, n

(array([100,  80,  50]), array([3, 4, 5]))

In [15]:
# 벡터의 내적을 구하는 방식 2가지 (1차원 배열은 전치를 하지 않고 계산 가능, 2차원 배열은 앞에 벡터를 전치해줘야한다.)
p @ n, np.dot(p, n)

(870, 870)