## [4주차] PCA를 통해 신체 지수 만들기

- sklearn의 Linnerrud 데이터셋은 피트니스 클럽의 20대 중반 남성 20명에 대해 
턱걸이, 윗몸일으키기, 점프 / 체중, 허리둘레, 맥박을 측정한 자료입니다.
  - ##### 요구사항1) Linnerrud 데이터셋의 상세 설명을 print 하세요
    - ##### *힌트1) .DESCR을 통해 데이터셋에 대한 설명을 알 수 있다.*
  
  - ##### 요구사항2) data와 target 매서드의 데이터를 모두 병합해 total이란 변수에 저장해주세요. [Chins, Situps, Jumps, Weight, Waist and Pulse] 순
    - ##### *힌트2) np.stack (vstack과 hstack 중 알맞은 것을 선택)

  - ##### 요구사항3) total 데이터를 1개의 차원으로 축소해 하나의 신체 지수를 body_index에 저장해주세요.

  - ##### 요구사항4) body_index를 다시 복원한 data를 recovered_data에 저장하고 total과 recovered_data를 각각 출력하세요

 - ##### 요구사항5) pca 변환을 통해 total의 분산을 몇% 나타내는지 explained_variance 변수에 저장하고 이를 소수 둘째 자리에서 반올림해 출력하세요.
  - * 힌트4) pca.explained_variance_ratio*
  - * 힌트5) type에러가 왜 발생하고, 어떻게 해결할 수 있을지 고민해보세요.

`

  - ##### 요구사항1) Linnerrud 데이터셋의 상세 설명을 print 하세요
    - ##### *힌트1) .DESCR을 통해 데이터셋에 대한 설명을 알 수 있다.

In [16]:
# 여기에 코드를 작성해주세요.

from sklearn.datasets import load_linnerud
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd

ll = load_linnerud()
print(ll.DESCR)

.. _linnerrud_dataset:

Linnerrud dataset
-----------------

**Data Set Characteristics:**

    :Number of Instances: 20
    :Number of Attributes: 3
    :Missing Attribute Values: None

The Linnerud dataset is a multi-output regression dataset. It consists of three
excercise (data) and three physiological (target) variables collected from
twenty middle-aged men in a fitness club:

- *physiological* - CSV containing 20 observations on 3 physiological variables:
   Weight, Waist and Pulse.
- *exercise* - CSV containing 20 observations on 3 exercise variables:
   Chins, Situps and Jumps.

.. topic:: References

  * Tenenhaus, M. (1998). La regression PLS: theorie et pratique. Paris:
    Editions Technic.



In [14]:
data = ll['data']
target = ll['target']

In [17]:
data[:5], target[:5]

(array([[  5., 162.,  60.],
        [  2., 110.,  60.],
        [ 12., 101., 101.],
        [ 12., 105.,  37.],
        [ 13., 155.,  58.]]),
 array([[191.,  36.,  50.],
        [189.,  37.,  52.],
        [193.,  38.,  58.],
        [162.,  35.,  62.],
        [189.,  35.,  46.]]))

In [21]:
data.shape, target.shape

((20, 3), (20, 3))

In [23]:
total = np.hstack((data, target))
print(total)

[[  5. 162.  60. 191.  36.  50.]
 [  2. 110.  60. 189.  37.  52.]
 [ 12. 101. 101. 193.  38.  58.]
 [ 12. 105.  37. 162.  35.  62.]
 [ 13. 155.  58. 189.  35.  46.]
 [  4. 101.  42. 182.  36.  56.]
 [  8. 101.  38. 211.  38.  56.]
 [  6. 125.  40. 167.  34.  60.]
 [ 15. 200.  40. 176.  31.  74.]
 [ 17. 251. 250. 154.  33.  56.]
 [ 17. 120.  38. 169.  34.  50.]
 [ 13. 210. 115. 166.  33.  52.]
 [ 14. 215. 105. 154.  34.  64.]
 [  1.  50.  50. 247.  46.  50.]
 [  6.  70.  31. 193.  36.  46.]
 [ 12. 210. 120. 202.  37.  62.]
 [  4.  60.  25. 176.  37.  54.]
 [ 11. 230.  80. 157.  32.  52.]
 [ 15. 225.  73. 156.  33.  54.]
 [  2. 110.  43. 138.  33.  68.]]


In [25]:
pca = PCA(n_components=1)
body_index = pca.fit_transform(total)
print(body_index)

[[  4.84819239]
 [-36.37337868]
 [-19.71530279]
 [-48.87880057]
 [ -1.24439301]
 [-52.7513643 ]
 [-59.41274725]
 [-32.28039126]
 [ 26.78843143]
 [192.82401404]
 [-37.38376798]
 [ 79.442903  ]
 [ 79.6880306 ]
 [-99.21237644]
 [-85.61627864]
 [ 76.83255115]
 [-94.42592828]
 [ 76.29783425]
 [ 68.59828074]
 [-38.02550839]]


In [26]:
#요구사항4

recovered_data = pca.inverse_transform(body_index)
print(total)
print(recovered_data)

[[  5. 162.  60. 191.  36.  50.]
 [  2. 110.  60. 189.  37.  52.]
 [ 12. 101. 101. 193.  38.  58.]
 [ 12. 105.  37. 162.  35.  62.]
 [ 13. 155.  58. 189.  35.  46.]
 [  4. 101.  42. 182.  36.  56.]
 [  8. 101.  38. 211.  38.  56.]
 [  6. 125.  40. 167.  34.  60.]
 [ 15. 200.  40. 176.  31.  74.]
 [ 17. 251. 250. 154.  33.  56.]
 [ 17. 120.  38. 169.  34.  50.]
 [ 13. 210. 115. 166.  33.  52.]
 [ 14. 215. 105. 154.  34.  64.]
 [  1.  50.  50. 247.  46.  50.]
 [  6.  70.  31. 193.  36.  46.]
 [ 12. 210. 120. 202.  37.  62.]
 [  4.  60.  25. 176.  37.  54.]
 [ 11. 230.  80. 157.  32.  52.]
 [ 15. 225.  73. 156.  33.  54.]
 [  2. 110.  43. 138.  33.  68.]]
[[  9.68240123 149.40974964  73.12363867 177.85161938  35.28616082
   56.1855779 ]
 [  7.70641862 116.59237538  49.11575846 184.21469709  36.2540741
   55.45795509]
 [  8.50493424 129.85422583  58.81759854 181.64330962  35.86293004
   55.75199522]
 [  7.10696316 106.63654159  41.83246811 186.1450692   36.54771075
   55.23721556]
 [  9.39

In [32]:
explained_variance = pca.explained_variance_ratio_
print(np.round(sum(explained_variance), 2))

0.78
